version: 2.1

jobs:
  test-xcode-10:
    macos:
      xcode: "10.0.0"
    steps:
      - setup
      - run-tests:
          destination: "platform=iOS Simulator,name=iPad Air 2,OS=12.0"

  test-xcode-9:
    macos:
      xcode: "9.3.0"
    steps:
      - setup
      - run-tests:
          destination: "platform=iOS Simulator,name=iPad Air 2,OS=10.3.1"

  deploy-to-cocoapods:
    macos:
      xcode: "10.0.0"
    steps:
      - setup
      - run: bundle exec pod trunk push

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  run-tests:
    description: "Runs the tests"
    parameters:
      destination:
        type: string
        default: "platform=iOS Simulator,name=iPad Air 2,OS=12.0"
    steps:
      - run: bundle exec fastlane test
      - run: bundle exec fastlane build_example destination:<< parameters.destination >>
      - run: bundle exec pod lib lint

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test-xcode-10:
          filters:
            tags:
              only: /.*/
      - test-xcode-9:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test-xcode-10
            - test-xcode-9
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
